UsersBundle\Entity\Eventos:
    type: entity
    table: Eventos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        place:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
