pruebas_homepage:
    path:     /
    defaults: { _controller: UsersBundle:Default:index }

get:
    path: getUsers
    defaults: { _controller: UsersBundle:Default:list }

email_not_nul: 
    path: emailNotNull
    defaults: {  _controller: UsersBundle:Default:listEamilNotNull }

new:
    path: newUser
    defaults: { _controller: UsersBundle:Default:insertUser }
    methods: POST

update:
    path: updateUser
    defaults: { _controller: UsersBundle:Default:updateUser }
    methods: POST

removeId:
    path: removeUserID/{id}
    defaults: { _controller: UsersBundle:Default:removeUserById }
    methods: GET