services:
#    pruebas.example:
#        class: UsersBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  users.user:
      class: UsersBundle\Services\UserService
      arguments: ["@doctrine.orm.entity_manager"]
      public: true
  
  